In [19]:
from IPython.display import Image
import numpy as np
import numpy.random as npr

a função arange funciona como um gerado de numeros para um determinado intervalo,a função nao inclue o limite superior.no codigo abaixo e usada a função arrange para gera uma sequencia de valores de um determinado intervalo (0 a 4) e salvo na variavel 'a', cada posiçao desse e vetor e multiplicado por 23,4 e salvo em um vetor 'b', apos isso os valores do vetor 'b' sao divididos pelos valores do vetor 'a'+1, e salvo no vetor c e adicionado +10  a cada pisição.

In [57]:
a = np.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10 
print (c)


[10.   21.7  25.6  27.55]


e possivel manipula vetores para que um seja o indice do vetor  como no caso abaixo .

In [58]:
arr = np.arange(100, 200)
select = [5, 25, 50, 75, -5]
print(arr[select])

[105 125 150 175 195]


e possivel fazer operaçoes de comparaçoes boleanos com vetores nesse caso ao apresenta a variavel boleana ela ira retorna verdadeiro ou falso para cada posição da variavel, nesse caso a variavel 'div_by_3'.E possivel ainda usa a vareavel bolena como indice para o vetor arr ele ira retorna os indices para qual o valor logico for vedadeiro.

In [61]:
 arr = np.arange(10, 20 )
div_by_3 = arr%3 == 0 
print(div_by_3)
print(arr[div_by_3]) 


[False False  True False False  True False False  True False]
[12 15 18]


como ja visto a função arange e usado para cria um vetor de X posicoes que vai de 'A' a 'Z'.caso quiséssemos gera uma matriz apartir de um determinado intervalo precisaremos usa a função reshape e necessario passa como parâmetro a quantidade linhas e colunas que a matriz dever ter.

In [71]:
arr = np.arange(10, 20) . reshape((2,5))
print (arr)

[[10 11 12 13 14]
 [15 16 17 18 19]]
